CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Cultures" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NULL,
    CONSTRAINT "PK_Cultures" PRIMARY KEY ("Id")
);

CREATE TABLE "Currencies" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NULL,
    CONSTRAINT "PK_Currencies" PRIMARY KEY ("Id")
);

CREATE TABLE "EntitiesBase" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DateCreated" timestamp without time zone NOT NULL,
    "Discriminator" text NOT NULL,
    "Playlist_SportId" integer NULL,
    "SportId" integer NULL,
    "PlaylistId" integer NULL,
    CONSTRAINT "PK_EntitiesBase" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EntitiesBase_EntitiesBase_SportId" FOREIGN KEY ("SportId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EntitiesBase_EntitiesBase_Playlist_SportId" FOREIGN KEY ("Playlist_SportId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EntitiesBase_EntitiesBase_PlaylistId" FOREIGN KEY ("PlaylistId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Images" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Path" text NULL,
    CONSTRAINT "PK_Images" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "SocialAccountProviders" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_SocialAccountProviders" PRIMARY KEY ("Id")
);

CREATE TABLE "SubscriptionsPlans" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Duration" interval NOT NULL,
    CONSTRAINT "PK_SubscriptionsPlans" PRIMARY KEY ("Id")
);

CREATE TABLE "EntitySaleablePrices" (
    "CurrencyId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Value" numeric NOT NULL,
    CONSTRAINT "PK_EntitySaleablePrices" PRIMARY KEY ("CurrencyId", "EntityId"),
    CONSTRAINT "FK_EntitySaleablePrices_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EntitySaleablePrices_EntitiesBase_EntityId" FOREIGN KEY ("EntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MovieTranslations" (
    "BaseEntityId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "ImageId" integer NULL,
    "Url" text NULL,
    CONSTRAINT "PK_MovieTranslations" PRIMARY KEY ("CultureId", "BaseEntityId"),
    CONSTRAINT "FK_MovieTranslations_EntitiesBase_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MovieTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MovieTranslations_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PlaylistsTranslations" (
    "BaseEntityId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "ImageId" integer NULL,
    CONSTRAINT "PK_PlaylistsTranslations" PRIMARY KEY ("CultureId", "BaseEntityId"),
    CONSTRAINT "FK_PlaylistsTranslations_EntitiesBase_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PlaylistsTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PlaylistsTranslations_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SportsTranslations" (
    "BaseEntityId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "ImageId" integer NULL,
    CONSTRAINT "PK_SportsTranslations" PRIMARY KEY ("CultureId", "BaseEntityId"),
    CONSTRAINT "FK_SportsTranslations_EntitiesBase_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SportsTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SportsTranslations_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "VideoTranslations" (
    "BaseEntityId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "ImageId" integer NULL,
    "Url" text NULL,
    CONSTRAINT "PK_VideoTranslations" PRIMARY KEY ("CultureId", "BaseEntityId"),
    CONSTRAINT "FK_VideoTranslations_EntitiesBase_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VideoTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VideoTranslations_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Users" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NULL,
    "Name" text NULL,
    "Password" text NULL,
    "AvatarId" integer NULL,
    "DateBirthday" timestamp without time zone NOT NULL,
    "DateSignUp" timestamp without time zone NOT NULL,
    "PhoneNumber" text NULL,
    "RoleId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "CurrencyId" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Images_AvatarId" FOREIGN KEY ("AvatarId") REFERENCES "Images" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Users_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Users_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SubscriptionPlanPrice" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Value" numeric NOT NULL,
    "CurrencyId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    CONSTRAINT "PK_SubscriptionPlanPrice" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SubscriptionPlanPrice_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SubscriptionPlanPrice_SubscriptionsPlans_EntityId" FOREIGN KEY ("EntityId") REFERENCES "SubscriptionsPlans" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SubscriptionsPlansTranslations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "BaseEntityId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    CONSTRAINT "PK_SubscriptionsPlansTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SubscriptionsPlansTranslations_SubscriptionsPlans_BaseEntit~" FOREIGN KEY ("BaseEntityId") REFERENCES "SubscriptionsPlans" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SubscriptionsPlansTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ConfirmationCodes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NULL,
    "Type" integer NOT NULL,
    "IsConfirmed" boolean NOT NULL,
    "UserId" integer NOT NULL,
    "DateValidUntil" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ConfirmationCodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConfirmationCodes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Favorites" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    CONSTRAINT "PK_Favorites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Favorites_EntitiesBase_EntityId" FOREIGN KEY ("EntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Favorites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Likes" (
    "UserId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "PK_Likes" PRIMARY KEY ("UserId", "EntityId"),
    CONSTRAINT "FK_Likes_EntitiesBase_EntityId" FOREIGN KEY ("EntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Likes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Payments" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NULL,
    "Value" numeric NOT NULL,
    "Status" integer NOT NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    "Type" integer NOT NULL,
    "UserId" integer NOT NULL,
    "CurrencyId" integer NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Payments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Sales" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    CONSTRAINT "PK_Sales" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sales_EntitiesBase_EntityId" FOREIGN KEY ("EntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Sales_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SocialAccounts" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NULL,
    "ProviderId" integer NOT NULL,
    "UserId" integer NULL,
    CONSTRAINT "PK_SocialAccounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SocialAccounts_SocialAccountProviders_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES "SocialAccountProviders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SocialAccounts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Subscriptions" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "DateStart" timestamp without time zone NOT NULL,
    "DateEnd" timestamp without time zone NOT NULL,
    "PlanId" integer NULL,
    "PaymentId" integer NULL,
    CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subscriptions_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Subscriptions_SubscriptionsPlans_PlanId" FOREIGN KEY ("PlanId") REFERENCES "SubscriptionsPlans" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Subscriptions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

INSERT INTO "Cultures" ("Id", "Key")
VALUES (1, 'ru');
INSERT INTO "Cultures" ("Id", "Key")
VALUES (2, 'en');

INSERT INTO "Currencies" ("Id", "Key")
VALUES (1, 'RUB');
INSERT INTO "Currencies" ("Id", "Key")
VALUES (2, 'EUR');
INSERT INTO "Currencies" ("Id", "Key")
VALUES (3, 'USD');

INSERT INTO "EntitiesBase" ("Id", "DateCreated", "Discriminator")
VALUES (1, TIMESTAMP '2020-06-28 19:07:37.248199', 'Sport');

INSERT INTO "Roles" ("Id", "Name")
VALUES (1, 'user');
INSERT INTO "Roles" ("Id", "Name")
VALUES (2, 'admin');

INSERT INTO "SocialAccountProviders" ("Id", "Name")
VALUES (1, 'google');
INSERT INTO "SocialAccountProviders" ("Id", "Name")
VALUES (2, 'vk');
INSERT INTO "SocialAccountProviders" ("Id", "Name")
VALUES (3, 'facebook');

INSERT INTO "EntitiesBase" ("Id", "DateCreated", "Discriminator", "SportId")
VALUES (4, TIMESTAMP '2020-06-28 19:07:37.248342', 'Movie', 1);

INSERT INTO "EntitiesBase" ("Id", "DateCreated", "Discriminator", "Playlist_SportId")
VALUES (2, TIMESTAMP '2020-06-28 19:07:37.248256', 'Playlist', 1);

INSERT INTO "EntitiesBase" ("Id", "DateCreated", "Discriminator", "PlaylistId")
VALUES (3, TIMESTAMP '2020-06-28 19:07:37.248316', 'Video', 2);

CREATE INDEX "IX_ConfirmationCodes_UserId" ON "ConfirmationCodes" ("UserId");

CREATE INDEX "IX_EntitiesBase_SportId" ON "EntitiesBase" ("SportId");

CREATE INDEX "IX_EntitiesBase_Playlist_SportId" ON "EntitiesBase" ("Playlist_SportId");

CREATE INDEX "IX_EntitiesBase_PlaylistId" ON "EntitiesBase" ("PlaylistId");

CREATE INDEX "IX_EntitySaleablePrices_EntityId" ON "EntitySaleablePrices" ("EntityId");

CREATE INDEX "IX_Favorites_EntityId" ON "Favorites" ("EntityId");

CREATE INDEX "IX_Favorites_UserId" ON "Favorites" ("UserId");

CREATE INDEX "IX_Likes_EntityId" ON "Likes" ("EntityId");

CREATE INDEX "IX_MovieTranslations_BaseEntityId" ON "MovieTranslations" ("BaseEntityId");

CREATE INDEX "IX_MovieTranslations_ImageId" ON "MovieTranslations" ("ImageId");

CREATE INDEX "IX_Payments_CurrencyId" ON "Payments" ("CurrencyId");

CREATE INDEX "IX_Payments_UserId" ON "Payments" ("UserId");

CREATE INDEX "IX_PlaylistsTranslations_BaseEntityId" ON "PlaylistsTranslations" ("BaseEntityId");

CREATE INDEX "IX_PlaylistsTranslations_ImageId" ON "PlaylistsTranslations" ("ImageId");

CREATE INDEX "IX_Sales_EntityId" ON "Sales" ("EntityId");

CREATE INDEX "IX_Sales_UserId" ON "Sales" ("UserId");

CREATE INDEX "IX_SocialAccounts_ProviderId" ON "SocialAccounts" ("ProviderId");

CREATE INDEX "IX_SocialAccounts_UserId" ON "SocialAccounts" ("UserId");

CREATE INDEX "IX_SportsTranslations_BaseEntityId" ON "SportsTranslations" ("BaseEntityId");

CREATE INDEX "IX_SportsTranslations_ImageId" ON "SportsTranslations" ("ImageId");

CREATE INDEX "IX_SubscriptionPlanPrice_CurrencyId" ON "SubscriptionPlanPrice" ("CurrencyId");

CREATE INDEX "IX_SubscriptionPlanPrice_EntityId" ON "SubscriptionPlanPrice" ("EntityId");

CREATE INDEX "IX_Subscriptions_PaymentId" ON "Subscriptions" ("PaymentId");

CREATE INDEX "IX_Subscriptions_PlanId" ON "Subscriptions" ("PlanId");

CREATE INDEX "IX_Subscriptions_UserId" ON "Subscriptions" ("UserId");

CREATE INDEX "IX_SubscriptionsPlansTranslations_BaseEntityId" ON "SubscriptionsPlansTranslations" ("BaseEntityId");

CREATE INDEX "IX_SubscriptionsPlansTranslations_CultureId" ON "SubscriptionsPlansTranslations" ("CultureId");

CREATE INDEX "IX_Users_AvatarId" ON "Users" ("AvatarId");

CREATE INDEX "IX_Users_CultureId" ON "Users" ("CultureId");

CREATE INDEX "IX_Users_CurrencyId" ON "Users" ("CurrencyId");

CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");

CREATE INDEX "IX_VideoTranslations_BaseEntityId" ON "VideoTranslations" ("BaseEntityId");

CREATE INDEX "IX_VideoTranslations_ImageId" ON "VideoTranslations" ("ImageId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200628190737_Init', '3.1.5');

ALTER TABLE "VideoTranslations" DROP CONSTRAINT "PK_VideoTranslations";

ALTER TABLE "SportsTranslations" DROP CONSTRAINT "PK_SportsTranslations";

ALTER TABLE "PlaylistsTranslations" DROP CONSTRAINT "PK_PlaylistsTranslations";

ALTER TABLE "MovieTranslations" DROP CONSTRAINT "PK_MovieTranslations";

ALTER TABLE "Likes" DROP CONSTRAINT "PK_Likes";

ALTER TABLE "EntitySaleablePrices" DROP CONSTRAINT "PK_EntitySaleablePrices";

ALTER TABLE "VideoTranslations" ADD CONSTRAINT "PK_VideoTranslations" PRIMARY KEY ("Id");

ALTER TABLE "SportsTranslations" ADD CONSTRAINT "PK_SportsTranslations" PRIMARY KEY ("Id");

ALTER TABLE "PlaylistsTranslations" ADD CONSTRAINT "PK_PlaylistsTranslations" PRIMARY KEY ("Id");

ALTER TABLE "MovieTranslations" ADD CONSTRAINT "PK_MovieTranslations" PRIMARY KEY ("Id");

ALTER TABLE "Likes" ADD CONSTRAINT "PK_Likes" PRIMARY KEY ("Id");

ALTER TABLE "EntitySaleablePrices" ADD CONSTRAINT "PK_EntitySaleablePrices" PRIMARY KEY ("Id");

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-06-29 10:55:05.818087'
WHERE "Id" = 4;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-06-29 10:55:05.818002'
WHERE "Id" = 2;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-06-29 10:55:05.817941'
WHERE "Id" = 1;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-06-29 10:55:05.818062'
WHERE "Id" = 3;

CREATE UNIQUE INDEX "IX_VideoTranslations_CultureId_BaseEntityId" ON "VideoTranslations" ("CultureId", "BaseEntityId");

CREATE UNIQUE INDEX "IX_SportsTranslations_CultureId_BaseEntityId" ON "SportsTranslations" ("CultureId", "BaseEntityId");

CREATE UNIQUE INDEX "IX_PlaylistsTranslations_CultureId_BaseEntityId" ON "PlaylistsTranslations" ("CultureId", "BaseEntityId");

CREATE UNIQUE INDEX "IX_MovieTranslations_CultureId_BaseEntityId" ON "MovieTranslations" ("CultureId", "BaseEntityId");

CREATE UNIQUE INDEX "IX_Likes_UserId_EntityId" ON "Likes" ("UserId", "EntityId");

CREATE UNIQUE INDEX "IX_EntitySaleablePrices_CurrencyId_EntityId" ON "EntitySaleablePrices" ("CurrencyId", "EntityId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200629105506_KeysFix', '3.1.5');

ALTER TABLE "SubscriptionPlanPrice" DROP CONSTRAINT "FK_SubscriptionPlanPrice_Currencies_CurrencyId";

ALTER TABLE "SubscriptionPlanPrice" DROP CONSTRAINT "FK_SubscriptionPlanPrice_SubscriptionsPlans_EntityId";

ALTER TABLE "SubscriptionPlanPrice" DROP CONSTRAINT "PK_SubscriptionPlanPrice";

ALTER TABLE "SubscriptionPlanPrice" RENAME TO "SubscriptionPlansPrices";

ALTER INDEX "IX_SubscriptionPlanPrice_EntityId" RENAME TO "IX_SubscriptionPlansPrices_EntityId";

ALTER INDEX "IX_SubscriptionPlanPrice_CurrencyId" RENAME TO "IX_SubscriptionPlansPrices_CurrencyId";

ALTER TABLE "SubscriptionPlansPrices" ADD CONSTRAINT "PK_SubscriptionPlansPrices" PRIMARY KEY ("Id");

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 16:04:51.097026'
WHERE "Id" = 4;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 16:04:51.09695'
WHERE "Id" = 2;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 16:04:51.096893'
WHERE "Id" = 1;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 16:04:51.097'
WHERE "Id" = 3;

ALTER TABLE "SubscriptionPlansPrices" ADD CONSTRAINT "FK_SubscriptionPlansPrices_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE CASCADE;

ALTER TABLE "SubscriptionPlansPrices" ADD CONSTRAINT "FK_SubscriptionPlansPrices_SubscriptionsPlans_EntityId" FOREIGN KEY ("EntityId") REFERENCES "SubscriptionsPlans" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200701160451_Ititi', '3.1.5');

ALTER TABLE "SocialAccounts" DROP CONSTRAINT "FK_SocialAccounts_SocialAccountProviders_ProviderId";

ALTER TABLE "SubscriptionPlansPrices" DROP CONSTRAINT "FK_SubscriptionPlansPrices_Currencies_CurrencyId";

ALTER TABLE "SubscriptionPlansPrices" DROP CONSTRAINT "FK_SubscriptionPlansPrices_SubscriptionsPlans_EntityId";

ALTER TABLE "SubscriptionPlansPrices" DROP CONSTRAINT "PK_SubscriptionPlansPrices";

ALTER TABLE "SocialAccountProviders" DROP CONSTRAINT "PK_SocialAccountProviders";

ALTER TABLE "SubscriptionPlansPrices" RENAME TO "SubscriptionsPlansPrices";

ALTER TABLE "SocialAccountProviders" RENAME TO "SocialAccountsProviders";

ALTER INDEX "IX_SubscriptionPlansPrices_EntityId" RENAME TO "IX_SubscriptionsPlansPrices_EntityId";

ALTER INDEX "IX_SubscriptionPlansPrices_CurrencyId" RENAME TO "IX_SubscriptionsPlansPrices_CurrencyId";

ALTER TABLE "SubscriptionsPlansPrices" ADD CONSTRAINT "PK_SubscriptionsPlansPrices" PRIMARY KEY ("Id");

ALTER TABLE "SocialAccountsProviders" ADD CONSTRAINT "PK_SocialAccountsProviders" PRIMARY KEY ("Id");

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 16:09:39.755788'
WHERE "Id" = 4;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 16:09:39.755707'
WHERE "Id" = 2;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 16:09:39.755649'
WHERE "Id" = 1;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 16:09:39.755758'
WHERE "Id" = 3;

ALTER TABLE "SocialAccounts" ADD CONSTRAINT "FK_SocialAccounts_SocialAccountsProviders_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES "SocialAccountsProviders" ("Id") ON DELETE CASCADE;

ALTER TABLE "SubscriptionsPlansPrices" ADD CONSTRAINT "FK_SubscriptionsPlansPrices_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE CASCADE;

ALTER TABLE "SubscriptionsPlansPrices" ADD CONSTRAINT "FK_SubscriptionsPlansPrices_SubscriptionsPlans_EntityId" FOREIGN KEY ("EntityId") REFERENCES "SubscriptionsPlans" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200701160940_Ititisd', '3.1.5');

ALTER TABLE "MovieTranslations" DROP CONSTRAINT "FK_MovieTranslations_EntitiesBase_BaseEntityId";

ALTER TABLE "MovieTranslations" DROP CONSTRAINT "FK_MovieTranslations_Cultures_CultureId";

ALTER TABLE "MovieTranslations" DROP CONSTRAINT "FK_MovieTranslations_Images_ImageId";

ALTER TABLE "VideoTranslations" DROP CONSTRAINT "FK_VideoTranslations_EntitiesBase_BaseEntityId";

ALTER TABLE "VideoTranslations" DROP CONSTRAINT "FK_VideoTranslations_Cultures_CultureId";

ALTER TABLE "VideoTranslations" DROP CONSTRAINT "FK_VideoTranslations_Images_ImageId";

ALTER TABLE "VideoTranslations" DROP CONSTRAINT "PK_VideoTranslations";

ALTER TABLE "MovieTranslations" DROP CONSTRAINT "PK_MovieTranslations";

ALTER TABLE "VideoTranslations" RENAME TO "VideosTranslations";

ALTER TABLE "MovieTranslations" RENAME TO "MoviesTranslations";

ALTER INDEX "IX_VideoTranslations_CultureId_BaseEntityId" RENAME TO "IX_VideosTranslations_CultureId_BaseEntityId";

ALTER INDEX "IX_VideoTranslations_ImageId" RENAME TO "IX_VideosTranslations_ImageId";

ALTER INDEX "IX_VideoTranslations_BaseEntityId" RENAME TO "IX_VideosTranslations_BaseEntityId";

ALTER INDEX "IX_MovieTranslations_CultureId_BaseEntityId" RENAME TO "IX_MoviesTranslations_CultureId_BaseEntityId";

ALTER INDEX "IX_MovieTranslations_ImageId" RENAME TO "IX_MoviesTranslations_ImageId";

ALTER INDEX "IX_MovieTranslations_BaseEntityId" RENAME TO "IX_MoviesTranslations_BaseEntityId";

ALTER TABLE "VideosTranslations" ADD CONSTRAINT "PK_VideosTranslations" PRIMARY KEY ("Id");

ALTER TABLE "MoviesTranslations" ADD CONSTRAINT "PK_MoviesTranslations" PRIMARY KEY ("Id");

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 16:11:16.20658'
WHERE "Id" = 4;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 16:11:16.2065'
WHERE "Id" = 2;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 16:11:16.206443'
WHERE "Id" = 1;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 16:11:16.206551'
WHERE "Id" = 3;

ALTER TABLE "MoviesTranslations" ADD CONSTRAINT "FK_MoviesTranslations_EntitiesBase_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE;

ALTER TABLE "MoviesTranslations" ADD CONSTRAINT "FK_MoviesTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE;

ALTER TABLE "MoviesTranslations" ADD CONSTRAINT "FK_MoviesTranslations_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT;

ALTER TABLE "VideosTranslations" ADD CONSTRAINT "FK_VideosTranslations_EntitiesBase_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE;

ALTER TABLE "VideosTranslations" ADD CONSTRAINT "FK_VideosTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE;

ALTER TABLE "VideosTranslations" ADD CONSTRAINT "FK_VideosTranslations_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200701161116_Ititik', '3.1.5');

CREATE TABLE "BannerEntities" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EntityId" integer NOT NULL,
    CONSTRAINT "PK_BannerEntities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BannerEntities_EntitiesBase_EntityId" FOREIGN KEY ("EntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE
);

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 17:45:24.523832'
WHERE "Id" = 4;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 17:45:24.523754'
WHERE "Id" = 2;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 17:45:24.523696'
WHERE "Id" = 1;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 17:45:24.523806'
WHERE "Id" = 3;

CREATE INDEX "IX_BannerEntities_EntityId" ON "BannerEntities" ("EntityId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200701174525_KLsl', '3.1.5');

ALTER TABLE "BannerEntities" DROP CONSTRAINT "FK_BannerEntities_EntitiesBase_EntityId";

ALTER TABLE "BannerEntities" ALTER COLUMN "EntityId" TYPE integer;
ALTER TABLE "BannerEntities" ALTER COLUMN "EntityId" DROP NOT NULL;
ALTER TABLE "BannerEntities" ALTER COLUMN "EntityId" DROP DEFAULT;

CREATE TABLE "BannerEntitiesTranslations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "BaseEntityId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    "Url" text NULL,
    "ImageId" integer NULL,
    CONSTRAINT "PK_BannerEntitiesTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BannerEntitiesTranslations_BannerEntities_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "BannerEntities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BannerEntitiesTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BannerEntitiesTranslations_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT
);

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 20:59:01.504931'
WHERE "Id" = 4;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 20:59:01.504848'
WHERE "Id" = 2;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 20:59:01.504789'
WHERE "Id" = 1;

UPDATE "EntitiesBase" SET "DateCreated" = TIMESTAMP '2020-07-01 20:59:01.504905'
WHERE "Id" = 3;

CREATE INDEX "IX_BannerEntitiesTranslations_BaseEntityId" ON "BannerEntitiesTranslations" ("BaseEntityId");

CREATE INDEX "IX_BannerEntitiesTranslations_ImageId" ON "BannerEntitiesTranslations" ("ImageId");

CREATE UNIQUE INDEX "IX_BannerEntitiesTranslations_CultureId_BaseEntityId" ON "BannerEntitiesTranslations" ("CultureId", "BaseEntityId");

ALTER TABLE "BannerEntities" ADD CONSTRAINT "FK_BannerEntities_EntitiesBase_EntityId" FOREIGN KEY ("EntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200701205902_banner', '3.1.5');

