CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Cultures" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NULL,
    CONSTRAINT "PK_Cultures" PRIMARY KEY ("Id")
);

CREATE TABLE "Currencies" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NULL,
    CONSTRAINT "PK_Currencies" PRIMARY KEY ("Id")
);

CREATE TABLE "EntitiesBase" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DateCreated" timestamp without time zone NOT NULL,
    "Discriminator" text NOT NULL,
    "Playlist_SportId" integer NULL,
    "SportId" integer NULL,
    "PlaylistId" integer NULL,
    CONSTRAINT "PK_EntitiesBase" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EntitiesBase_EntitiesBase_SportId" FOREIGN KEY ("SportId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EntitiesBase_EntitiesBase_Playlist_SportId" FOREIGN KEY ("Playlist_SportId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EntitiesBase_EntitiesBase_PlaylistId" FOREIGN KEY ("PlaylistId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Images" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Path" text NULL,
    CONSTRAINT "PK_Images" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "SocialAccountsProviders" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_SocialAccountsProviders" PRIMARY KEY ("Id")
);

CREATE TABLE "SubscriptionsPlans" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Duration" interval NOT NULL,
    "Color" text NULL,
    CONSTRAINT "PK_SubscriptionsPlans" PRIMARY KEY ("Id")
);

CREATE TABLE "BannerEntities" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EntityId" integer NULL,
    CONSTRAINT "PK_BannerEntities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BannerEntities_EntitiesBase_EntityId" FOREIGN KEY ("EntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "EntitySaleablePrices" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Value" numeric NOT NULL,
    "CurrencyId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    CONSTRAINT "PK_EntitySaleablePrices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EntitySaleablePrices_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EntitySaleablePrices_EntitiesBase_EntityId" FOREIGN KEY ("EntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MoviesTranslations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "BaseEntityId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    "ImageId" integer NULL,
    "Url" text NULL,
    CONSTRAINT "PK_MoviesTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MoviesTranslations_EntitiesBase_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MoviesTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MoviesTranslations_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PlaylistsTranslations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "BaseEntityId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    "ImageId" integer NULL,
    CONSTRAINT "PK_PlaylistsTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PlaylistsTranslations_EntitiesBase_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PlaylistsTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PlaylistsTranslations_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SportsTranslations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "BaseEntityId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    "ImageId" integer NULL,
    CONSTRAINT "PK_SportsTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SportsTranslations_EntitiesBase_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SportsTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SportsTranslations_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "VideosTranslations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "BaseEntityId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    "ImageId" integer NULL,
    "Url" text NULL,
    CONSTRAINT "PK_VideosTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VideosTranslations_EntitiesBase_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VideosTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VideosTranslations_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Users" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NULL,
    "Name" text NULL,
    "Password" text NULL,
    "AvatarId" integer NULL,
    "DateBirthday" timestamp without time zone NOT NULL,
    "DateSignUp" timestamp without time zone NOT NULL,
    "PhoneNumber" text NULL,
    "RoleId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "CurrencyId" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Images_AvatarId" FOREIGN KEY ("AvatarId") REFERENCES "Images" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Users_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Users_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PromoCodes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NULL,
    "SubscriptionPlanId" integer NULL,
    "EntitySaleableId" integer NULL,
    "IsInfinite" boolean NOT NULL,
    "IsValid" boolean NOT NULL,
    CONSTRAINT "PK_PromoCodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PromoCodes_EntitiesBase_EntitySaleableId" FOREIGN KEY ("EntitySaleableId") REFERENCES "EntitiesBase" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PromoCodes_SubscriptionsPlans_SubscriptionPlanId" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionsPlans" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SubscriptionsPlansPrices" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Value" numeric NOT NULL,
    "DiscountValue" numeric NOT NULL,
    "CurrencyId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    CONSTRAINT "PK_SubscriptionsPlansPrices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SubscriptionsPlansPrices_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SubscriptionsPlansPrices_SubscriptionsPlans_EntityId" FOREIGN KEY ("EntityId") REFERENCES "SubscriptionsPlans" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SubscriptionsPlansTranslations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "BaseEntityId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    CONSTRAINT "PK_SubscriptionsPlansTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SubscriptionsPlansTranslations_SubscriptionsPlans_BaseEntit~" FOREIGN KEY ("BaseEntityId") REFERENCES "SubscriptionsPlans" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SubscriptionsPlansTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BannerEntitiesTranslations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "BaseEntityId" integer NOT NULL,
    "CultureId" integer NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    "Url" text NULL,
    "ImageId" integer NULL,
    CONSTRAINT "PK_BannerEntitiesTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BannerEntitiesTranslations_BannerEntities_BaseEntityId" FOREIGN KEY ("BaseEntityId") REFERENCES "BannerEntities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BannerEntitiesTranslations_Cultures_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Cultures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BannerEntitiesTranslations_Images_ImageId" FOREIGN KEY ("ImageId") REFERENCES "Images" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ConfirmationCodes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NULL,
    "Type" integer NOT NULL,
    "IsConfirmed" boolean NOT NULL,
    "UserId" integer NOT NULL,
    "DateValidUntil" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ConfirmationCodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConfirmationCodes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Favorites" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    CONSTRAINT "PK_Favorites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Favorites_EntitiesBase_EntityId" FOREIGN KEY ("EntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Favorites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Likes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    CONSTRAINT "PK_Likes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Likes_EntitiesBase_EntityId" FOREIGN KEY ("EntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Likes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Payments" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NULL,
    "Value" numeric NOT NULL,
    "Status" integer NOT NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    "Type" integer NOT NULL,
    "UserId" integer NOT NULL,
    "CurrencyId" integer NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Payments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Sales" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    CONSTRAINT "PK_Sales" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sales_EntitiesBase_EntityId" FOREIGN KEY ("EntityId") REFERENCES "EntitiesBase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Sales_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SocialAccounts" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NULL,
    "ProviderId" integer NOT NULL,
    "UserId" integer NULL,
    CONSTRAINT "PK_SocialAccounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SocialAccounts_SocialAccountsProviders_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES "SocialAccountsProviders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SocialAccounts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PromoCodesUsers" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PromoCodeId" integer NOT NULL,
    CONSTRAINT "PK_PromoCodesUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PromoCodesUsers_PromoCodes_PromoCodeId" FOREIGN KEY ("PromoCodeId") REFERENCES "PromoCodes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PromoCodesUsers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Subscriptions" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "DateStart" timestamp without time zone NOT NULL,
    "DateEnd" timestamp without time zone NOT NULL,
    "PlanId" integer NULL,
    "PaymentId" integer NULL,
    CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subscriptions_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Subscriptions_SubscriptionsPlans_PlanId" FOREIGN KEY ("PlanId") REFERENCES "SubscriptionsPlans" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Subscriptions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

INSERT INTO "Cultures" ("Id", "Key")
VALUES (1, 'ru');
INSERT INTO "Cultures" ("Id", "Key")
VALUES (2, 'en');

INSERT INTO "Currencies" ("Id", "Key")
VALUES (1, 'RUB');
INSERT INTO "Currencies" ("Id", "Key")
VALUES (2, 'EUR');
INSERT INTO "Currencies" ("Id", "Key")
VALUES (3, 'USD');

INSERT INTO "EntitiesBase" ("Id", "DateCreated", "Discriminator")
VALUES (1, TIMESTAMP '2020-09-26 15:42:14.489766', 'Sport');

INSERT INTO "Roles" ("Id", "Name")
VALUES (1, 'user');
INSERT INTO "Roles" ("Id", "Name")
VALUES (2, 'admin');

INSERT INTO "SocialAccountsProviders" ("Id", "Name")
VALUES (1, 'google');
INSERT INTO "SocialAccountsProviders" ("Id", "Name")
VALUES (2, 'vk');
INSERT INTO "SocialAccountsProviders" ("Id", "Name")
VALUES (3, 'facebook');

INSERT INTO "EntitiesBase" ("Id", "DateCreated", "Discriminator", "SportId")
VALUES (4, TIMESTAMP '2020-09-26 15:42:14.489919', 'Movie', 1);

INSERT INTO "EntitiesBase" ("Id", "DateCreated", "Discriminator", "Playlist_SportId")
VALUES (2, TIMESTAMP '2020-09-26 15:42:14.489836', 'Playlist', 1);

INSERT INTO "EntitiesBase" ("Id", "DateCreated", "Discriminator", "PlaylistId")
VALUES (3, TIMESTAMP '2020-09-26 15:42:14.489892', 'Video', 2);

CREATE INDEX "IX_BannerEntities_EntityId" ON "BannerEntities" ("EntityId");

CREATE INDEX "IX_BannerEntitiesTranslations_BaseEntityId" ON "BannerEntitiesTranslations" ("BaseEntityId");

CREATE INDEX "IX_BannerEntitiesTranslations_ImageId" ON "BannerEntitiesTranslations" ("ImageId");

CREATE UNIQUE INDEX "IX_BannerEntitiesTranslations_CultureId_BaseEntityId" ON "BannerEntitiesTranslations" ("CultureId", "BaseEntityId");

CREATE INDEX "IX_ConfirmationCodes_UserId" ON "ConfirmationCodes" ("UserId");

CREATE INDEX "IX_EntitiesBase_SportId" ON "EntitiesBase" ("SportId");

CREATE INDEX "IX_EntitiesBase_Playlist_SportId" ON "EntitiesBase" ("Playlist_SportId");

CREATE INDEX "IX_EntitiesBase_PlaylistId" ON "EntitiesBase" ("PlaylistId");

CREATE INDEX "IX_EntitySaleablePrices_EntityId" ON "EntitySaleablePrices" ("EntityId");

CREATE UNIQUE INDEX "IX_EntitySaleablePrices_CurrencyId_EntityId" ON "EntitySaleablePrices" ("CurrencyId", "EntityId");

CREATE INDEX "IX_Favorites_EntityId" ON "Favorites" ("EntityId");

CREATE INDEX "IX_Favorites_UserId" ON "Favorites" ("UserId");

CREATE INDEX "IX_Likes_EntityId" ON "Likes" ("EntityId");

CREATE UNIQUE INDEX "IX_Likes_UserId_EntityId" ON "Likes" ("UserId", "EntityId");

CREATE INDEX "IX_MoviesTranslations_BaseEntityId" ON "MoviesTranslations" ("BaseEntityId");

CREATE INDEX "IX_MoviesTranslations_ImageId" ON "MoviesTranslations" ("ImageId");

CREATE UNIQUE INDEX "IX_MoviesTranslations_CultureId_BaseEntityId" ON "MoviesTranslations" ("CultureId", "BaseEntityId");

CREATE INDEX "IX_Payments_CurrencyId" ON "Payments" ("CurrencyId");

CREATE INDEX "IX_Payments_UserId" ON "Payments" ("UserId");

CREATE INDEX "IX_PlaylistsTranslations_BaseEntityId" ON "PlaylistsTranslations" ("BaseEntityId");

CREATE INDEX "IX_PlaylistsTranslations_ImageId" ON "PlaylistsTranslations" ("ImageId");

CREATE UNIQUE INDEX "IX_PlaylistsTranslations_CultureId_BaseEntityId" ON "PlaylistsTranslations" ("CultureId", "BaseEntityId");

CREATE INDEX "IX_PromoCodes_EntitySaleableId" ON "PromoCodes" ("EntitySaleableId");

CREATE INDEX "IX_PromoCodes_SubscriptionPlanId" ON "PromoCodes" ("SubscriptionPlanId");

CREATE INDEX "IX_PromoCodesUsers_UserId" ON "PromoCodesUsers" ("UserId");

CREATE UNIQUE INDEX "IX_PromoCodesUsers_PromoCodeId_UserId" ON "PromoCodesUsers" ("PromoCodeId", "UserId");

CREATE INDEX "IX_Sales_EntityId" ON "Sales" ("EntityId");

CREATE UNIQUE INDEX "IX_Sales_UserId_EntityId" ON "Sales" ("UserId", "EntityId");

CREATE INDEX "IX_SocialAccounts_ProviderId" ON "SocialAccounts" ("ProviderId");

CREATE INDEX "IX_SocialAccounts_UserId" ON "SocialAccounts" ("UserId");

CREATE INDEX "IX_SportsTranslations_BaseEntityId" ON "SportsTranslations" ("BaseEntityId");

CREATE INDEX "IX_SportsTranslations_ImageId" ON "SportsTranslations" ("ImageId");

CREATE UNIQUE INDEX "IX_SportsTranslations_CultureId_BaseEntityId" ON "SportsTranslations" ("CultureId", "BaseEntityId");

CREATE INDEX "IX_Subscriptions_PaymentId" ON "Subscriptions" ("PaymentId");

CREATE INDEX "IX_Subscriptions_PlanId" ON "Subscriptions" ("PlanId");

CREATE INDEX "IX_Subscriptions_UserId" ON "Subscriptions" ("UserId");

CREATE INDEX "IX_SubscriptionsPlansPrices_CurrencyId" ON "SubscriptionsPlansPrices" ("CurrencyId");

CREATE INDEX "IX_SubscriptionsPlansPrices_EntityId" ON "SubscriptionsPlansPrices" ("EntityId");

CREATE INDEX "IX_SubscriptionsPlansTranslations_BaseEntityId" ON "SubscriptionsPlansTranslations" ("BaseEntityId");

CREATE INDEX "IX_SubscriptionsPlansTranslations_CultureId" ON "SubscriptionsPlansTranslations" ("CultureId");

CREATE INDEX "IX_Users_AvatarId" ON "Users" ("AvatarId");

CREATE INDEX "IX_Users_CultureId" ON "Users" ("CultureId");

CREATE INDEX "IX_Users_CurrencyId" ON "Users" ("CurrencyId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");

CREATE INDEX "IX_VideosTranslations_BaseEntityId" ON "VideosTranslations" ("BaseEntityId");

CREATE INDEX "IX_VideosTranslations_ImageId" ON "VideosTranslations" ("ImageId");

CREATE UNIQUE INDEX "IX_VideosTranslations_CultureId_BaseEntityId" ON "VideosTranslations" ("CultureId", "BaseEntityId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200926154215_Init', '3.1.5');

